### ISSUE TITLE
Disable if PRIME profiles are not supported 

### ISSUE THREAD

**Issue by mirkobrombin** [Vanilla-OS/vanilla-prime-utility#57]
Replaces: https://github.com/Vanilla-OS/gnome-control-center/issues/35

**Comment by kbdharun** [comment]
Hi, Does this mean prime utility will be added to the desktop image too but will show a disabled message instead?

**Comment by mirkobrombin** [comment]
I just noticed that this is already the case, in the case of an incompatible device an information screen appears.

> Hi, Does this mean prime utility will be added to the desktop image too but will show a disabled message instead?

Yes
